#pragma once

namespace ds {

	enum ChunkType {
		CHNK_GUI = 0,
		CHNK_DLG_DEF,
		CHNK_DLG_IMAGE,
		CHNK_DLG_BUTTON,
		CHNK_DLG_TEXT,
		CHNK_FONT,
		CHNK_PARTICLE_DATA,
		CHNK_RING_EMITTER,
		CHNK_EMITTER_DATA,
		CHNK_PARTICLE_SIZE,
		CHNK_PARTICLE_COLOR,
		CHNK_PARTICLE_VELOCITY,
		CHNK_PARTICLE_ROTATION,
		CHNK_SPRITE,
		CHNK_PARTICLESYSTEM,
		CHNK_BLOOM_COMPONENT,
		CHNK_BOX_EMITTER,
		CHNK_SPRITE_DESCRIPTION,
		CHNK_DLG_IMAGE_LINK,
		CHNK_DESCRIPTOR,
		CHNK_MESH,
		CHNK_DLG_NUMBERS,
		CHNK_DLG_TIMER
	};


}